### ISSUE TITLE
EOFException: End of input at line 1 column 1 path $

### ISSUE THREAD

**Issue by t-nasu** [gyro-n/gopay-java-sdk#164] opened 2018-10-25 05:47 UTC
Sometime authentication or creating a charge request result in `EOFException` like:

```
! @798mlfc05 - Internal server error, for (POST) [/admin/authenticate] ->
play.api.UnexpectedException: Unexpected exception[EOFException: End of input at line 1 column 1 path $]
at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:251)
at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
...
Caused by: java.io.EOFException: End of input at line 1 column 1 path $
at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1401)
at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549)
at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:205)
at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39)
at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
at jp.gopay.sdk.builders.RetrofitRequestCaller.extractModel(RetrofitRequestCaller.java:116)
at jp.gopay.sdk.builders.RetrofitRequestCaller.dispatch(RetrofitRequestCaller.java:77)
at jp.gopay.sdk.builders.RetrofitRequestCaller.dispatch(RetrofitRequestCaller.java:19)
at remote.WithCallback.$anonfun$handleCallbackWithFuture$1(RemoteLoginHandler.scala:27)
at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:655)
at scala.util.Success.$anonfun$map$1(Try.scala:251)
at scala.util.Success.map(Try.scala:209)
at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
... 13 common frames omitted
```

**Comment by justinian336** [comment] 2018-10-25 13:44
@t-nasu can you provide any way of replicating this error, or any hint on the type of response that causes it.

**Comment by t-nasu** [comment] 2018-10-26 03:07
I also can not reproduce it certainly. we need some way to get more context.

**Comment by justinian336** [comment] 2018-10-26 03:35
It looks like it's caused by an empty response from the server. I remember we addressed a similar issue before, I'll try to replicate it and see if we're missing some rare case in our tests.

**Comment by justinian336** [comment] 2018-12-17 04:36
I'm closing this issue until someone else can reproduce it.

**Closed by justinian336** 2018-12-17 04:36 UTC
